export enum ErrorCode {
  VALIDATION = 'VALIDATION_ERROR',
  AUTHENTICATION = 'AUTHENTICATION_ERROR',
  AUTHORIZATION = 'AUTHORIZATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  PROVIDER = 'PROVIDER_ERROR',
  DATABASE = 'DATABASE_ERROR',
  BUSINESS_RULE = 'BUSINESS_RULE_ERROR',
  INTERNAL = 'INTERNAL_ERROR',
}
