/**
 * Exports the real OpenAPI document to packages/api-contracts/openapi.yaml.
 *
 * Reuses the exact same Swagger config the app already mounts at /docs in
 * dev (see ../src/bootstrap/swagger.ts's buildOpenApiDocument) — this script
 * does not define a second, divergent Swagger setup. It boots the full Nest
 * application (so every real controller/route/DTO is scanned) but never
 * calls app.listen(), so no HTTP server is actually started.
 *
 * Run: npm run export:openapi
 */
import { NestFactory } from '@nestjs/core';
import * as yaml from 'js-yaml';
import * as fs from 'fs';
import * as path from 'path';
import { AppModule } from '../src/app.module';
import { configureApp } from '../src/bootstrap/app';
import { buildOpenApiDocument } from '../src/bootstrap/swagger';

async function main(): Promise<void> {
  const app = await NestFactory.create(AppModule, { logger: false });
  configureApp(app); // same global prefix + versioning the real app serves under
  await app.init();

  const document = buildOpenApiDocument(app);
  // cwd-relative (not __dirname-relative) so this resolves the same whether run
  // via ts-node (scripts/) or the compiled build (dist/scripts/) — always run
  // via `npm run export:openapi` from apps/backend.
  const outPath = path.resolve(process.cwd(), '../../packages/api-contracts/openapi.yaml');
  const header =
    '# Generated by apps/backend/scripts/export-openapi.ts — do not hand-edit.\n' +
    '# Source of truth: @nestjs/swagger decorators on the real controllers/DTOs\n' +
    '# (see apps/backend/src/bootstrap/swagger.ts). Regenerate with:\n' +
    '#   cd apps/backend && npm run export:openapi\n';
  fs.writeFileSync(outPath, header + yaml.dump(document, { noRefs: true, lineWidth: -1 }));

  // eslint-disable-next-line no-console
  console.log(`OpenAPI spec written to ${outPath}`);
  await app.close();
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error('OpenAPI export failed:', e);
  process.exit(1);
});
